name: Test

on:
  - push
  - pull_request

jobs:
  tests:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.12"
          - python: "3.11"
          - python: "3.10"
          - python: "3.9"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade tox

      - name: Run tests
        env:
          TOXENV: py-wtforms31, py-wtforms32
        run: tox
